Playwright tests. Check command for lint and coverage of vue and django. Removed selenium stuff. Update CI stuff. .coveragerc for Python.

diff --git a/run b/run
--- a/run
+++ b/run
@@ -12,24 +12,24 @@ docker-compose up -d
 
 function init() {
   echo "Running idempotent init script"
+  # Since we don't have "if not exists" we just attempt it.
   docker-compose exec db psql -U postgres -c "create database db;"
   docker-compose exec webdev python3 -m venv /code/venv
   docker-compose exec webdev /code/venv/bin/python3 -m pip install -r /code/backend/requirements.txt
   docker-compose exec webdev /code/venv/bin/python3 /code/backend/manage.py migrate
-  # todo break this out into own npm command?
   docker-compose exec jsdev npm install
 }
 
 function clean() {
   # Since docker is run as root, its generated files are root owned
-  docker-compose exec webdev rm -rf /code/venv && \
-    rm -rf /code/pgdata && \
-    rm -rf /code/vueapp/node_modules && \
-    rm -rf /code/backend/static && \
-    rm -rf /code/htmlcov && \
-    rm /code/.coverage && \
-    rm -rf /code/vueapp/coverage && \
-    rm /code/backend/app/static/app/webpack-dist
+  docker-compose exec webdev rm -rf /code/venv
+  docker-compose exec webdev rm -rf /code/pgdata
+  docker-compose exec webdev rm -rf /code/vueapp/node_modules
+  docker-compose exec webdev rm -rf /code/backend/static
+  docker-compose exec webdev rm -rf /code/htmlcov
+  docker-compose exec webdev rm -f /code/.coverage
+  docker-compose exec webdev rm -rf /code/vueapp/coverage
+  docker-compose exec webdev rm -rf /code/backend/app/static/app/webpack-dist
 }
 
 function django-manage() {
@@ -45,20 +45,20 @@ function django-test() {
 }
 
 function django-test-coverage() {
-  docker-compose exec webdev /code/venv/bin/coverage run /code/backend/manage.py test app
-  docker-compose exec webdev /code/venv/bin/coverage report
-  docker-compose exec webdev /code/venv/bin/coverage html
+  set -eu
+  docker-compose exec webdev /code/venv/bin/coverage run --rcfile=/code/backend/.coveragerc /code/backend/manage.py test app
+  docker-compose exec webdev /code/venv/bin/coverage report --rcfile=/code/backend/.coveragerc
+  docker-compose exec webdev /code/venv/bin/coverage html --rcfile=/code/backend/.coveragerc
   read -e -p "Open coverage report in browser? [Y/n] " YN
   [[ $YN == "y" || $YN == "Y" || $YN == "" ]] && open htmlcov/index.html
 }
-
 
 function pip() {
  docker-compose exec webdev /code/venv/bin/pip3 "$@"
 }
 
 function black() {
- docker-compose exec webdev /code/venv/bin/black backend
+ docker-compose exec webdev /code/venv/bin/black backend "$@"
 }
 
 function npm() {
@@ -97,6 +97,23 @@ function help() {
   echo "Tasks:"
   compgen -A function | cat -n
 }
+
+function checkall() {
+  set -eu
+  # fail if Vue standard not met
+  vue-cli lint --no-fix
+  #fail if tests fails or coverage is not met
+  vue-cli test:unit --coverage
+  vue-build
+  # fails if Python linting standard not met
+  black --check
+  # fails if tests fail
+  docker-compose exec webdev /code/venv/bin/coverage run --rcfile=/code/backend/.coveragerc /code/backend/manage.py test app
+  # fails if coverage is not met
+  docker-compose exec webdev /code/venv/bin/coverage report --rcfile=/code/backend/.coveragerc
+  echo All steps in check-all were successful
+}
+
 
 # This command executes help function by default
 "${@:-help}"
